name: Rich Mattas
favicon: null
layout_spectrum: 0.11597324372269213
typography_spectrum: 0.10976862139068544
title: Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9fcde7'
    - '#000000'
    - '#a77e5e'
    - '#3d4b00'
    - '#ffecca'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
